#!/bin/bash

export ROS_DISTRO=humble
export UNDERLAY_WS=/opt/ros/${ROS_DISTRO}
export OVERLAY_WS=~/ros/workspaces/test_ws
export ROS_DOMAIN_ID=7
export ROS_NAMESPACE=robot1
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export RCUTILS_CONSOLE_OUTPUT_FORMAT='[{severity}]: {message}'
export RCUTILS_COLORIZED_OUTPUT=1
export RCUTILS_LOGGING_USE_STDOUT=0
export RCUTILS_LOGGING_BUFFERED_STREAM=0

alias cw='cd ~/robot_ws'
alias cs='cd ~/robot_ws/src'
alias ccd='colcon_cd'

alias cb='cd ~/robot_ws && colcon build --symlink=install'
alias cbs='colcon build --symlink-install'
alias cbp='colcon build --symlink-install --packages-select'
alias cbu='colcon build --symlink-install --packages-up-to'
alias ct='colcon test'
alias ctp='colcon test --packages-select'
alias ctr='colcon test-result'

alias rt='ros2 topic list'
alias re='ros2 topic echo'
alias rn='ros2 node list'

alias killgazebo='killall -9 gazebo & killall -9 gzserver & killall -9 gzclient'

alias af='ament_flake8'
alias ac='ament_cpplint'

alias testpub='ros2 run demo_nodes_cpp talker'
alias testsub='ros2 run demo_nodes_cpp listener'
alias testpubimg='ros2 run image_tools cam2image'
alias testsubimg='ros2 run image_tools showimage'

alias torws="cd ${OVERLAY_WS}"

source ${UNDERLAY_WS}/setup.bash
source ${OVERLAY_WS}/install/local_setup.bash


# colcon
source /usr/share/colcon_cd/function/colcon_cd.sh
export _colcon_cd_root=${OVERLAY_WS}
source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

# GIT_SSL_CAINFO=/etc/ssl/certs/HMGSecureROOTCA.crt